### ISSUE TITLE
Do you only focus on unsupervised sequence similarity/distance? How to consider functional similarity/distance?

### ISSUE THREAD

**Issue by xinshao-wang** [gcorso/NeuroSEED#3]
Dear authors, 

Greetings!

I would like to check do you only focus on unsupervised sequence similarities/distances of biological sequences? If so, do you have a plan to consider their functional similarities/distances?

Thanks. 
(Amos) Xinshao Wang

**Comment by gcorso** [comment]
Hi Amos,
Indeed we only focus on unsupervised similarities and have no plans of considering functional ones, but we believe many of the method's components could be reused in that setting.
Gabriele

**Comment by xinshao-wang** [comment]
Hi Gabriele, 

Thanks so much for your reply. 

I have been also working on diverse bioseq distances, e.g., MMSeq2, HMMer, deep embedding distance metrics, etc. I look forward to future discussion with you. This is my profile: https://www.linkedin.com/in/xinshaowang/

Amos
